# Generated by Django 5.1.1 on 2024-11-01 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_remove_usetf_industry_remove_usetf_sector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brrealestate',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='brrealestate',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='brstock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='brstock',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='usetf',
            name='category',
        ),
        migrations.RemoveField(
            model_name='usstock',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='usstock',
            name='sector',
        ),
    ]
