# Generated by Django 5.1.1 on 2024-11-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0005_remove_brtreasure_title_brtreasure_title_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brtreasure',
            old_name='title_type',
            new_name='title',
        ),
    ]
