# Generated by Django 5.1.1 on 2024-11-06 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0007_brtreasure_title_type_alter_brtreasure_maturity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brtreasure',
            name='maturity',
        ),
        migrations.RemoveField(
            model_name='brtreasure',
            name='title_type',
        ),
    ]
