# Generated by Django 5.1.1 on 2024-11-07 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0008_remove_brtreasure_maturity_and_more'),
        ('search', '0003_alter_brrealestate_options_alter_brstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brrealestate',
            options={'ordering': ['ticker'], 'verbose_name': 'FIIs'},
        ),
        migrations.AlterModelOptions(
            name='brstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações BR'},
        ),
        migrations.AlterModelOptions(
            name='brtreasure',
            options={'ordering': ['title'], 'verbose_name': 'Tesouro Direto'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['ticker'], 'verbose_name': 'Criptomoedas'},
        ),
        migrations.AlterModelOptions(
            name='usetf',
            options={'ordering': ['ticker'], 'verbose_name': 'ETFs US'},
        ),
        migrations.AlterModelOptions(
            name='usstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações US'},
        ),
        migrations.RemoveField(
            model_name='brtreasure',
            name='profitability',
        ),
        migrations.AddField(
            model_name='brtreasure',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='br_realestates', to='search.brrealestate', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='br_stocks', to='search.brstock', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='br_treasures', to='search.brtreasure', verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cryptos', to='search.crypto', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_etfs', to='search.usetf', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='date',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='price',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='us_stocks', to='search.usstock', verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
