# Generated by Django 5.1.1 on 2024-11-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0010_alter_brrealestate_options_alter_brstock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketDataStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=50, null=True)),
                ('data_inicio', models.CharField(blank=True, max_length=10, null=True)),
                ('model', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estatística',
                'ordering': ['model'],
            },
        ),
    ]
