# Generated by Django 5.1.1 on 2024-11-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0011_marketdatastats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MarketDataStats',
            new_name='Stats',
        ),
    ]
