# Generated by Django 5.1.1 on 2024-11-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0012_rename_marketdatastats_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brrealestate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Preço'),
        ),
    ]
