# Generated by Django 5.1.1 on 2024-11-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econdata', '0002_remove_cryptodata_created_at_remove_cryptodata_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoData',
        ),
    ]
