# Generated by Django 5.1.1 on 2024-11-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('econdata', '0003_delete_cryptodata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brcdi',
            options={'ordering': ['date'], 'verbose_name': 'CDI', 'verbose_name_plural': 'CDI'},
        ),
        migrations.AlterModelOptions(
            name='brinflation',
            options={'ordering': ['date'], 'verbose_name': 'Inflação BR', 'verbose_name_plural': 'Inflação BR'},
        ),
        migrations.AlterModelOptions(
            name='brinterestrate',
            options={'ordering': ['date'], 'verbose_name': 'Taxa de Juros BR', 'verbose_name_plural': 'Taxa de Juros BR'},
        ),
        migrations.AlterModelOptions(
            name='commodityprice',
            options={'ordering': ['date'], 'verbose_name': 'Commodities', 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='cumulativebrcdi',
            options={'ordering': ['date'], 'verbose_name': 'CDI Acumulado', 'verbose_name_plural': 'CDI Acumulado'},
        ),
        migrations.AlterModelOptions(
            name='cumulativebrinflation',
            options={'ordering': ['date'], 'verbose_name': 'Inflação Acumulada BR', 'verbose_name_plural': 'Inflação Acumulada BR'},
        ),
        migrations.AlterModelOptions(
            name='dollarexchangerate',
            options={'ordering': ['date'], 'verbose_name': 'Dólar', 'verbose_name_plural': 'Dólar'},
        ),
        migrations.AlterModelOptions(
            name='usinflation',
            options={'ordering': ['date'], 'verbose_name': 'Inflação US', 'verbose_name_plural': 'Inflação US'},
        ),
        migrations.AlterModelOptions(
            name='usinterestrate',
            options={'ordering': ['date'], 'verbose_name': 'Taxa de Juros US', 'verbose_name_plural': 'Taxa de Juros US'},
        ),
        migrations.AlterField(
            model_name='brcdi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brcdi',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brcdi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brcdi',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='brinflation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brinflation',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brinflation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brinflation',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='brinterestrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brinterestrate',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='brinterestrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brinterestrate',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='commodityprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='commodityprice',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='commodityprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='commodityprice',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cumulativebrcdi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cumulativebrcdi',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cumulativebrcdi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cumulativebrcdi',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='cumulativebrinflation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='cumulativebrinflation',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cumulativebrinflation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='cumulativebrinflation',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='dollarexchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='dollarexchangerate',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='dollarexchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='dollarexchangerate',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='usinflation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usinflation',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='usinflation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usinflation',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='usinterestrate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usinterestrate',
            name='date',
            field=models.DateField(unique=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='usinterestrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usinterestrate',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
