# Generated by Django 5.1.1 on 2024-11-07 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('econdata', '0004_alter_brcdi_options_alter_brinflation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brcdi',
            options={'ordering': ['-date'], 'verbose_name': 'CDI', 'verbose_name_plural': 'CDI'},
        ),
        migrations.AlterModelOptions(
            name='brinflation',
            options={'ordering': ['-date'], 'verbose_name': 'Inflação BR', 'verbose_name_plural': 'Inflação BR'},
        ),
        migrations.AlterModelOptions(
            name='brinterestrate',
            options={'ordering': ['-date'], 'verbose_name': 'Taxa de Juros BR', 'verbose_name_plural': 'Taxa de Juros BR'},
        ),
        migrations.AlterModelOptions(
            name='commodityprice',
            options={'ordering': ['-date'], 'verbose_name': 'Commodities', 'verbose_name_plural': 'Commodities'},
        ),
        migrations.AlterModelOptions(
            name='cumulativebrcdi',
            options={'ordering': ['-date'], 'verbose_name': 'CDI Acumulado', 'verbose_name_plural': 'CDI Acumulado'},
        ),
        migrations.AlterModelOptions(
            name='cumulativebrinflation',
            options={'ordering': ['-date'], 'verbose_name': 'Inflação Acumulada BR', 'verbose_name_plural': 'Inflação Acumulada BR'},
        ),
        migrations.AlterModelOptions(
            name='dollarexchangerate',
            options={'ordering': ['-date'], 'verbose_name': 'Dólar', 'verbose_name_plural': 'Dólar'},
        ),
        migrations.AlterModelOptions(
            name='usinflation',
            options={'ordering': ['-date'], 'verbose_name': 'Inflação US', 'verbose_name_plural': 'Inflação US'},
        ),
        migrations.AlterModelOptions(
            name='usinterestrate',
            options={'ordering': ['-date'], 'verbose_name': 'Taxa de Juros US', 'verbose_name_plural': 'Taxa de Juros US'},
        ),
    ]
