# Generated by Django 5.1.1 on 2024-11-08 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0005_alter_brrealestate_options_alter_brstock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data')),
                ('event_type', models.CharField(max_length=200, verbose_name='Evento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_br_realestates', to='search.brrealestate', verbose_name='Código')),
            ],
            options={
                'verbose_name': 'FIIs',
                'verbose_name_plural': 'FIIs',
            },
        ),
        migrations.CreateModel(
            name='BrStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data')),
                ('event_type', models.CharField(max_length=200, verbose_name='Evento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_br_stocks', to='search.brstock', verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ações BR',
                'verbose_name_plural': 'Ações BR',
            },
        ),
        migrations.CreateModel(
            name='UsEtf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data')),
                ('event_type', models.CharField(max_length=200, verbose_name='Evento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_us_etfs', to='search.usetf', verbose_name='Código')),
            ],
            options={
                'verbose_name': 'ETFs US',
                'verbose_name_plural': 'ETFs US',
            },
        ),
        migrations.CreateModel(
            name='UsStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Data')),
                ('event_type', models.CharField(max_length=200, verbose_name='Evento')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events_us_stocks', to='search.usstock', verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Ações US',
                'verbose_name_plural': 'Ações US',
            },
        ),
    ]
