# Generated by Django 5.1.1 on 2024-11-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usetf',
            old_name='industry',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='usetf',
            name='sector',
        ),
    ]
