# Generated by Django 5.1.1 on 2024-11-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_industry_usetf_category_remove_usetf_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brrealestate',
            options={'ordering': ['ticker'], 'verbose_name': 'FIIs'},
        ),
        migrations.AlterModelOptions(
            name='brstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações BR'},
        ),
        migrations.AlterModelOptions(
            name='brtreasure',
            options={'ordering': ['title'], 'verbose_name': 'Tesouro Direto'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['ticker'], 'verbose_name': 'Criptomoedas'},
        ),
        migrations.AlterModelOptions(
            name='usetf',
            options={'ordering': ['ticker'], 'verbose_name': 'ETFs US'},
        ),
        migrations.AlterModelOptions(
            name='usstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações US'},
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='industry',
            field=models.CharField(max_length=200, verbose_name='Indústria'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='sector',
            field=models.CharField(max_length=200, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='industry',
            field=models.CharField(max_length=200, verbose_name='Indústria'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='sector',
            field=models.CharField(max_length=200, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='brstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='maturity',
            field=models.DateField(verbose_name='Vencimento'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='title_type',
            field=models.CharField(max_length=200, verbose_name='Tipo de Título'),
        ),
        migrations.AlterField(
            model_name='brtreasure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='category',
            field=models.CharField(max_length=200, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usetf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='industry',
            field=models.CharField(max_length=200, verbose_name='Indústria'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='sector',
            field=models.CharField(max_length=200, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='ticker',
            field=models.CharField(max_length=30, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='usstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
