# Generated by Django 5.1.1 on 2024-11-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_brrealestate_options_alter_brstock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brrealestate',
            options={'ordering': ['ticker'], 'verbose_name': 'FIIs', 'verbose_name_plural': 'FIIs'},
        ),
        migrations.AlterModelOptions(
            name='brstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações BR', 'verbose_name_plural': 'Ações BR'},
        ),
        migrations.AlterModelOptions(
            name='brtreasure',
            options={'ordering': ['title'], 'verbose_name': 'Tesouro Direto', 'verbose_name_plural': 'Tesouro Direto'},
        ),
        migrations.AlterModelOptions(
            name='crypto',
            options={'ordering': ['ticker'], 'verbose_name': 'Criptomoedas', 'verbose_name_plural': 'Criptomoedas'},
        ),
        migrations.AlterModelOptions(
            name='usetf',
            options={'ordering': ['ticker'], 'verbose_name': 'ETFs US', 'verbose_name_plural': 'ETFs US'},
        ),
        migrations.AlterModelOptions(
            name='usstock',
            options={'ordering': ['ticker'], 'verbose_name': 'Ações US', 'verbose_name_plural': 'Ações US'},
        ),
    ]
