# Generated by Django 5.1.1 on 2024-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_brrealestate_options_alter_brstock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brrealestate',
            name='segment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='brstock',
            name='segment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='usetf',
            name='segment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='usstock',
            name='segment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Segmento'),
        ),
    ]
