# Generated by Django 5.1.1 on 2024-11-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_brrealestate_segment_brstock_segment_usetf_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brrealestate',
            name='segment',
        ),
        migrations.AlterField(
            model_name='brrealestate',
            name='sector',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
    ]
