# Generated by Django 5.1.1 on 2024-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_alter_brrealestate_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brrealestate',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='brrealestate',
            name='sector',
        ),
        migrations.AddField(
            model_name='brrealestate',
            name='segment',
            field=models.CharField(default=0, max_length=200, verbose_name='Segmento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brrealestate',
            name='type',
            field=models.CharField(default=0, max_length=200, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
