# Generated by Django 5.1.1 on 2024-11-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_remove_usstock_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usetf',
            name='segment',
        ),
    ]
